# Generated by Django 4.0.6 on 2022-07-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedescription',
            name='file_extension',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filedescription',
            name='uniform_size',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
